name: Deploy n8n Workflow

on:
  push:
    paths:
      - 'telegram_echo_workflow.json'
      - '.github/workflows/n8n_deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy workflow to n8n
        env:
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
          N8N_HOST: ${{ secrets.N8N_HOST }}
        run: |
          curl -X POST \
            -H "X-N8N-API-KEY: $N8N_API_KEY" \
            -H "Content-Type: application/json" \
            --data-binary @telegram_echo_workflow.json \
            "$N8N_HOST/api/v1/workflows" 